# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  main stack

Resources:
  NestedStack1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested-1.yaml

  NestedStack2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested-2.yaml

