# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Nested-1 stack - empty

Conditions:
  FalseCondition: !Equals [ 'true', 'false' ]

Resources:
  NullResource:
    Type: 'Custom::NullResource'
    Condition: FalseCondition

  ServiceCatalogPortfolioProduct:
    Type: 'AWS::ServiceCatalog::CloudFormationProduct'
    Properties:
      Name: 'ServiceCatalog-Product-Example'
      Description: 'Example'
      Owner: 'package-cfn'
      ProvisioningArtifactParameters:
        - Name: 'package-cfn'
          Description: 'Example'
          Info:
            LoadTemplateFromURL: 'https://s3.amazonaws.com/< S3_CFN_STAGING_BUCKET_PATH >/nested-1-1.yaml'